### ISSUE TITLE
Instrukcja

### ISSUE THREAD

**Issue by keradus** [danan72/kindle-pw2-l10n-pl#5]
Byłbym wdzięczny, gdyby pojawiła się instrukcja jak te polonizacje wgrywać

**Comment by danan72** [comment]
Instrukcja instalacji krok-po-kroku jest w plikach **czytaj-mnie** dołączanych do spolszczenia, np. https://github.com/danan72/kindle-pw2-l10n-pl/blob/master/loc_hack/src/README_5.4.3.1 , oraz w opisie release'u https://github.com/danan72/kindle-pw2-l10n-pl/releases/tag/fw5.4.3.1

**Comment by keradus** [comment]
Wielkie dzięki !
